/**
 * Recommendation Engine Version
 *
 * This identifier is attached to every OutfitSet generated by the engine so that
 * we can trace which version produced a recommendation in production logs and
 * analytics — critical for debugging and rollback decisions after launch.
 *
 * Increment the patch when a validated, regression-tested change ships.
 * Never change this value without a corresponding benchmark run.
 */
export const RECOMMENDATION_ENGINE_VERSION = '3.7' as const;
export type RecommendationEngineVersion = typeof RECOMMENDATION_ENGINE_VERSION;
