uploads = []
outputs = []

[[generated]]
id = "uvAAYwuQ37cVsIjrc3rV2"
uri = "file://assets/recommendations/beige_crop_top.png"
type = "image"
title = "beige crop top"

[[generated]]
id = "NzhGm-saTnWt9WohaU0ux"
uri = "file://assets/recommendations/denim_mini_skirt.png"
type = "image"
title = "denim mini skirt"

[[generated]]
id = "KqLXPx9jnau1CEuksWUdw"
uri = "file://assets/recommendations/grey_hoodie.png"
type = "image"
title = "grey hoodie"

[[generated]]
id = "rfUZx6KOKqwhZV27nqwRf"
uri = "file://assets/recommendations/satin_bomber.png"
type = "image"
title = "satin bomber"

[[generated]]
id = "dkwLfsBQUhl044AfHZCRc"
uri = "file://assets/recommendations/high_waist_jeans.png"
type = "image"
title = "high waist jeans"

[[generated]]
id = "-6Yvf3TAlvYDvIur2VmOB"
uri = "file://assets/recommendations/oversized_blazer.png"
type = "image"
title = "oversized blazer"

[[generated]]
id = "Bkqrh3Ofkxub6TuapVjLX"
uri = "file://assets/recommendations/casual_slip_dress.png"
type = "image"
title = "casual slip dress"

[[generated]]
id = "3Q1TRIeeo7CRX3iKzzn2_"
uri = "file://assets/recommendations/denim_jacket.png"
type = "image"
title = "denim jacket"

[[generated]]
id = "OciFuSf0zc3Ruzw5utW4G"
uri = "file://assets/recommendations/chunky_trainers.png"
type = "image"
title = "chunky trainers"

[[generated]]
id = "pdmh6IdHkiGckpLqgB7UT"
uri = "file://assets/recommendations/chunky_gold_chain.png"
type = "image"
title = "chunky gold chain necklace"

[[generated]]
id = "MgtHNAhdvkmNM2owSHOmf"
uri = "file://assets/recommendations/beige_satin_midi.png"
type = "image"
title = "beige satin midi skirt"

[[generated]]
id = "pR8Lb1JRUO92Ev5g8AQu5"
uri = "file://assets/recommendations/floral_blush_maxi_skirt.png"
type = "image"
title = "floral blush maxi skirt"

[[generated]]
id = "jZh-r5660vweUqoXlotFN"
uri = "file://assets/recommendations/grey_trousers.png"
type = "image"
title = "grey trousers"

[[generated]]
id = "EEHhVg6pjWDZKL71LZBkk"
uri = "file://assets/recommendations/dark_slim_jeans.png"
type = "image"
title = "dark slim jeans"

[[generated]]
id = "9eh4VQ8f8BiBmd_pT1Omf"
uri = "file://assets/recommendations/gold_stacking_rings.png"
type = "image"
title = "gold stacking rings"

[[generated]]
id = "_r8RU2fo87dow467Xkydy"
uri = "file://assets/recommendations/navy_wide_leg_trousers.png"
type = "image"
title = "navy wide leg trousers"

[[generated]]
id = "xHdege4w1CFbqtCqhHuVo"
uri = "file://assets/recommendations/black_silk_slip_dress.png"
type = "image"
title = "black silk slip midi dress"

[[generated]]
id = "6oNrQ3OPpmDJw8QgZCQIs"
uri = "file://assets/recommendations/gold_drop_earrings.png"
type = "image"
title = "gold drop earrings"

[[generated]]
id = "zC8lpbA39thDP1BBMg--p"
uri = "file://assets/recommendations/black_cutout_crop_top.png"
type = "image"
title = "black cutout crop top"

[[generated]]
id = "Y1PdhubPXqkTKStCSXi2d"
uri = "file://assets/recommendations/red_pencil_skirt.png"
type = "image"
title = "red pencil midi skirt"

[[generated]]
id = "1WuyBP9ZVMGa4RrjBdPg4"
uri = "file://assets/recommendations/black_bodycon_dress.png"
type = "image"
title = "black bodycon mini dress"

[[generated]]
id = "8ePGxI2huWdGCfqNJxQ32"
uri = "file://assets/recommendations/black_leather_moto.png"
type = "image"
title = "black leather moto jacket"
