// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/wardrobe-variants/ColumnGrid.tsx": () => import("../components/mockups/wardrobe-variants/ColumnGrid.tsx"),
  "./components/mockups/wardrobe-variants/HorizontalList.tsx": () => import("../components/mockups/wardrobe-variants/HorizontalList.tsx")
};
